<?php

/**
 * @file
 * earn_it_form_tweaks.module - Earn It Form Tweaks code.
 *
 * @author
 * Shawn FitzPatrick sdfitzpa@asu.edu
 *
 * Provides form tweaks for the add activity form
 *
 */

/*********************************************************************
  CONFIG
*********************************************************************/


/*********************************************************************
  DRUPAL HOOKS
*********************************************************************/

/**
 * Implements hook_form_alter().
 *
 */
function earn_it_form_tweaks_form_alter(&$form, &$form_state, $form_id) {

  switch($form_id) {

    case 'game_node_form':
    
      global $user;
      $account = $user;
      
      $cpath = current_path();
      drupal_set_message($cpath);
      if ($cpath == "node/add/game") {
    
        $randomSerial = rand(1000, 10000);
        // TODO: check its not a duplicate
      
        $form['title']['#default_value'] = "game" . $randomSerial;

        $form['field_serial_number']['und'][0]['value']['#default_value'] = $randomSerial;
        $form['field_serial_number']['#disabled'] = true;
        $form['field_facilitator']['und']['#default_value'] = $account->uid;
        $form['field_facilitator']['#disabled'] = true;
        $form['field_current_game_state']['#disabled'] = true;
      
        $form['#submit'][] = 'add_users_to_game';
      
      }
     
      break;

    }
}

/*********************************************************************
  API
*********************************************************************/

function add_users_to_game($form, &$form_state) {
  drupal_set_message($form['field_serial_number']['und'][0]['value']['#default_value']);
}
