<?php

/**
 * @file
 * earn_it_form_tweaks.module - Earn It Form Tweaks code.
 *
 * @author
 * Shawn FitzPatrick sdfitzpa@asu.edu
 *
 * Provides form tweaks for the add activity form
 *
 */

/*********************************************************************
  CONFIG
*********************************************************************/


/*********************************************************************
  DRUPAL HOOKS
*********************************************************************/

/**
 * Implements hook_form_alter().
 *
 */
function earn_it_form_tweaks_form_alter(&$form, &$form_state, $form_id) {

  switch($form_id) {

    case 'game_node_form':
    
      global $user;
      $account = $user;
      
      $cpath = current_path();
      drupal_set_message($cpath);
      if ($cpath == "node/add/game") {
      
        $testUser = user_load(2);
        dpm($testUser);
    
        $randomSerial = rand(1000, 10000);
        // TODO: check its not a duplicate
      
        $form['title']['#default_value'] = "game" . $randomSerial;

        $form['field_serial_number']['und'][0]['value']['#default_value'] = $randomSerial;
        //$form['field_serial_number']['#disabled'] = true;
        $form['field_facilitator']['und']['#default_value'] = $account->uid;
        $form['field_facilitator']['#disabled'] = true;
        $form['field_current_game_state']['#disabled'] = true;
      
        //$form['#submit'][] = 'add_users_to_game';
      
      }
     
      break;

    }
}

function earn_it_form_tweaks_node_update($node) {
  dpm($node);
}

/*********************************************************************
  API
*********************************************************************/

function add_users_to_game($form, &$form_state) {
  drupal_set_message("value #value" . $form['field_serial_number']['und'][0]['value']['#value']);
  dpm($form);
  //field_playing_game set to nid of the game
  // maybe und 0 target_id #value
  // field_team_color is going ot be tid of the color
  // und #default_value 0 but try #value
  // field_student_state set to tid of init so 1
  // try und #value 0 set to 1
  // 16 - 23 for colors
  
  $gnid = 71;
  $gameNum = $form['field_serial_number']['und'][0]['value']['#value'];
  $gtitle = "game" . $gameNum;
  
  $result = db_query("SELECT n.nid FROM node n WHERE n.title = (:ntitle)", array(':ntitle' => $gtitle)); 
  foreach($result as $record) {
    $gnid = $record -> nid;
    print $record -> nid;
  } 

  $edit = array(
    'name' => $gameNum . 'maroon',
    'pass' => $gameNum . 'maroon',
    // grab the color from the actual tid
    // and incremet the tid when I put this in a loop
    'status' => 1,
    'field_student_state' => array(
      'und' => array(
        0 => array(
          "tid" => 1))),
    'field_playing_game' => array(
      'und' => array(
        0 => array(
          "target_id" => $gnid))),
    'field_team_color' => array(
      'und' => array(
        0 => array(
          "tid" => 16))),
  );
  user_save(null, $edit);
}
