<?php

/**
 * @file
 * earn_it_activity_tweaks.module - Earn It Activity Tweaks code.
 *
 * @author
 * Shawn FitzPatrick sdfitzpa@asu.edu
 *
 * Provides form tweaks for the add activity form
 *
 */

/*********************************************************************
  CONFIG
*********************************************************************/


/*********************************************************************
  DRUPAL HOOKS
*********************************************************************/

/**
 * Implements hook_form_alter().
 *
 */
function earn_it_activity_tweaks_form_alter(&$form, &$form_state, $form_id) {

  global $user;
  if ($user->uid ==1)
    dpm($form);

  switch($form_id) {

    case 'activity_node_form':

      // Conditionally hide fields based on checked state of $form['field_variable_time']
      $form['field_min_hours']['#states'] = array(
        // Only show this field when the 'field_variable_time' checkbox is enabled.
        'visible' => array(
          ':input[id=edit-field-variable-time-und]' => array('checked' => TRUE),
          ),
        );
      $form['field_max_hours']['#states'] = array(
        // Only show this field when the 'field_variable_time' checkbox is enabled.
        'visible' => array(
          ':input[id=edit-field-variable-time-und]' => array('checked' => TRUE),
          ),
        );
      $form['field_scholarship_per_hour']['#states'] = array(
        // Only show this field when the 'field_variable_time' checkbox is enabled.
        'visible' => array(
          ':input[id=edit-field-variable-time-und]' => array('checked' => TRUE),
          ),
        );
        
      $form['field_hours']['#states'] = array(
        // Only show this field when the 'field_variable_time' checkbox is disabled.
        'visible' => array(
          ':input[id=edit-field-variable-time-und]' => array('checked' => FALSE),
          ),
        );
      $form['field_scholarship']['#states'] = array(
        // Only show this field when the 'field_variable_time' checkbox is disabled.
        'visible' => array(
          ':input[id=edit-field-variable-time-und]' => array('checked' => FALSE),
          ),
        );

      break;
  }
}

