<?php
/**
 * @file
 * login based on team color and game number
 * 
 * @author Chandi Cumaranatunge (chandima@asu.edu)
 */


/*********************************************************************
 DRUPAL HOOKS
*********************************************************************/

/**
 * Implements hook_block_info().
 */
function earn_it_login_tweaks_block_info() {
  $blocks['earn_it_login_form'] = array(
      'info' => t('Earn It Login'),
  );

  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function earn_it_login_tweaks_block_view($delta = '') {
  switch ($delta) {
    case 'earn_it_login_form':
      $block['subject'] = t('Login');
      $block['content'] = earn_it_login_form_content();;
      break;
  }
  return $block;
}


/**
 * Implements hook_form_alter().
 */
function earn_it_login_tweaks_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  //dpm($form_id);
  switch ($form_id) {
    case 'user_login':
      
      // add fieldset
      $form['default_login'] = array(
          '#type' => 'fieldset',
          '#title' => t('Default Login'),
          '#collapsible' => TRUE,
          '#collapsed' => TRUE,
          '#tree' => TRUE,
      );
      
      // move default login elements inside fieldset
      $form['default_login']['name'] = $form['name'];
      $form['default_login']['pass'] = $form['pass'];
      $form['default_login']['actions'] = $form['actions'];
      
      // disable access to default login elements
      $form['name']['#access'] = FALSE;
      $form['pass']['#access'] = FALSE;
      $form['actions']['#access'] = FALSE;
      
      // add new validation function at the head of the validation chain
      array_unshift($form['#validate'] , 'earn_it_login_form_pre_validation_actions');

      break;
      
    case 'user_login_form':
      $form['name']['#access'] = FALSE;
      $form['title']['#printed'] = true;
      $form['name']['#printed'] = true;

      break;
  }
}


/*********************************************************************
 FORMS
*********************************************************************/

function earn_it_login_form($form, &$form_state) {
  
  $terms = taxonomy_get_tree(5);
  $terms_select = array();
  foreach ($terms as $term) {
   $terms_select[$term->tid] = str_repeat('-', $term->depth) . $term->name;
  }
  $form['team_color'] = array(
    '#type' => 'select',
    '#title' => t('Team Color'),
    '#options' => drupal_map_assoc(array('Maroon', 'Gold', 'Gray', 'Orange', 'Blue')),
    '#required' => TRUE,
  );
  
  $form['game_number'] = array(
      '#type' => 'textfield',
      '#title' => t('Game Number'),
      '#size' => 8,
      '#maxlength' => 8,
      //'#required' => TRUE,
  );

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Login',
  );

  
  return $form;
}


/*********************************************************************
 CALLBACKS
*********************************************************************/

/**
 * Login form submit function
 *   Login or register user
 * @param array $form
 * @param array $form_state
 */
function earn_it_login_form_submit($form, &$form_state) {
  if (isset($form_state['values']['op'])) {
    switch ($form_state['values']['op']) {
      
      
     case 'Login':
      //validation has already checked that this is a valid user
       if (isset($form_state['values']['team_color']) && $form_state['values']['team_color'] && isset($form_state['values']['game_number']) && $form_state['values']['game_number']) {
         global $user;
         $user = user_load_by_name($form_state['values']['game_number'].$form_state['values']['team_color']);
         drupal_session_regenerate();
         drupal_goto('student');
       }
      break;
    }
  }
}

/**
 * First validation function in the user login
 *   form validation chain. Does some housekeeping
 *   to restore values into the default login form fields.
 * @param array $form
 * @param array $form_state
 */
function earn_it_login_form_pre_validation_actions($form, &$form_state) {
  // copy values from inside fieldset to required login fields
  if (isset($form_state['values'])) {
    $form_state['values']['name'] = $form_state['values']['default_login']['name'];
    $form_state['values']['pass'] = $form_state['values']['default_login']['pass'];
  }
}

/**
 * PGI Login form validation
 *   Checks if ID code valid if Login
 * @param array $form
 * @param array $form_state
 */
function earn_it_login_form_validate($form, &$form_state) {
  if (isset($form_state['values']['op'])) {
    switch ($form_state['values']['op']) {
      case 'Login':
        if (isset($form_state['values']['team_color']) && $form_state['values']['team_color'] && isset($form_state['values']['game_number']) && $form_state['values']['game_number']) {
             return true;
        } else {
          form_set_error('id_code', t('Team color and game number required.'));
        }
        break;
      }
   }
}


/*********************************************************************
 UTILITY
*********************************************************************/


/**
 * Custom ID based login form
 * @return string
 */
function earn_it_login_form_content() {
  $html = '';
  $html .= drupal_render(drupal_get_form('earn_it_login_form'));
  return $html;
}
